[project]
name = "tdchess"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "matplotlib>=3.10.3",
    "numpy>=2.2.6",
    "onnx>=1.18.0",
    "onnxruntime>=1.22.0",
    "torch>=2.7.1",
]
