name: C/C++ CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build_and_test:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Install dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y build-essential cmake wget unzip
        wget https://download.pytorch.org/libtorch/cpu/libtorch-cxx11-abi-shared-with-deps-latest%2Bcpu.zip -O libtorch.zip
        unzip libtorch.zip
        rm libtorch.zip

    - name: Create build directory
      run: mkdir build && cd build

    - name: Configure CMake
      # The extracted folder is named 'libtorch', so CMAKE_PREFIX_PATH should point to it.
      run: cd build && cmake .. -DCMAKE_PREFIX_PATH=$GITHUB_WORKSPACE/libtorch -DWITH_GPU_SUPPORT=OFF

    - name: Build
      run: cd build && cmake --build .

    - name: Run tests
      run: cd build && ./TDChess test 3
